### ISSUE TITLE
Potential vignettes

### ISSUE THREAD

**Issue by usamabilal** [heli-xu/findSVI#9]
I was thinking that the feature i like the most about packages and that makes me use them more are vignettes! I highly suggest creating one. Could potentially have two:

- mapping of  SVI at different levels , leveraging tidycensus and sf
- application of obtaining SVI at the ZCTA level and correlations with disease (for example COVID, which has plenty of zip code level data). Would need to find a reliable source of ZCTA data that will continue being available over time

**Comment by heli-xu** [comment]
Hi Usama, I finally feel ready to give you some updates about the "findSVI" package. It's available for download through github, and the documentation/vignettes can be viewed [here](https://heli-xu.github.io/findSVI/). 

I moved your issue to this repo and I'm looking forward to picking up our discussion from here.  So far there're 3 vignettes:
- [Mapping SVI at ZCTA level for PA (2020).](https://heli-xu.github.io/findSVI/articles/SVI-mapping.html)
- [SVI and health outcome: ](https://heli-xu.github.io/findSVI/articles/svi-covid.html)Looking at the correlation between ZCTA-level covid and svi in Philadelphia (using the very helpful COVID-19 Health Inequities in Cities Dashboard). The results are similar to what was shown on the dashboard. You're right, zcta-level disease data are quite hard to find...
- [ Putting SVI in context:](https://heli-xu.github.io/findSVI/articles/tract-level_SVI_in_Philly.html) This is something Ran brought up, and I found it very interesting to see how SVI is affected by the area taken into account during calculation. 


Thank you again for your help with getting the package "in shape", and I'd appreciate any further feedback and suggestions!

**Comment by usamabilal** [comment]
Thanks Heli! This is amazing! A few comments:

- The Mapping SVI one looks great!
- For the health outcomes one: I suggest you look at hospitalizations if available (i think they are for Philly). Deaths are tricky because of age, and incidence is tricky because of testing
- I dont fully follow the putting SVI in context one. Shouldnt census tract calculation be exaclty the same in the CDC one vs the package? The curved relationship seems weird to me! I wasnt expecting that. After all, a re-ranking (going from just PHilly to all of PA) should still show the same correlation, just with shifted intercepts

Just one comment in the putting SVI in context:

**Comment by heli-xu** [comment]
Thanks Usama!
>I suggest you look at hospitalizations if available (i think they are for Philly). 

Indeed deaths and incidence can be tricky...Working on the the updates with hospitalizations.

>a re-ranking (going from just PHilly to all of PA) should still show the same correlation, just with shifted intercepts.

That's a great question! I wasn't actually sure and maybe still am not sure I get it 100%, but after some digging I updated the vignette with [some more discussions](https://heli-xu.github.io/findSVI/articles/tract-level_SVI_in_Philly.html) and would very much like to hear what you think. 

Thanks again for your help!

**Comment by heli-xu** [comment]
Hi Usama, here is the [updated vignette](https://heli-xu.github.io/findSVI/articles/svi-covid.html) looking at SVI and hospitalization data. Thanks!

**Comment by usamabilal** [comment]
> Hi Usama, here is the [updated vignette](https://heli-xu.github.io/findSVI/articles/svi-covid.html) looking at SVI and hospitalization data. Thanks!

Excellent! this looks great.

**Comment by usamabilal** [comment]
> That's a great question! I wasn't actually sure and maybe still am not sure I get it 100%, but after some digging I updated the vignette with [some more discussions](https://heli-xu.github.io/findSVI/articles/tract-level_SVI_in_Philly.html) and would very much like to hear what you think.
> 
> Thanks again for your help!

Thanks for doing this! If i am understanding things right, the reason behind the discrepancies is that STA (summarize [percentile] then analyze [mean]) is different than ATS (analyze then summarize): so if you take the percentiles for PHL and then calculate the SVI, you are going to get a different result than if you take the percentiles for all of PA and then restrict to PA?

**Comment by heli-xu** [comment]
>if you take the percentiles for PHL and then calculate the SVI, you are going to get a different result than if you take the percentiles for all of PA and then restrict to PA (PHL)?

I agree with this second part, and the "restrict to PHL" is a simple filter without any manipulation. 
But I'm not sure I understand the first part:

>the reason behind the discrepancies is that STA (summarize [percentile] then analyze [mean]) is different than ATS (analyze then summarize):

To clarify, both findSVI and CDC calculate SVI by taking the percentile, adding up all variables for each tract, then taking the percentile again of the sum and that's the SVI. The only difference is what area (how many total tracts) the percentile is taken against. Maybe it's because I'm not very familiar with the terminology here, but the order of summarize and analyze doesn't seem different to me. I remember we did encounter this STA and ATS problem before when we were aggregating (summarizing) the CDC tract-level SVI to zcta-level and compare it with our result (and realized it's not a good idea), whereas in this case I don't see a summarizing step...did you mean something else by summarize?

If we take CDC's nation-level SVI and restrict to Philly, it'll also look different from PA-level SVI restricted to Philly. When we study Philly, we might prefer using PA-level SVI from CDC than their nation-level SVI. I think it's a similar idea, and having more locally relevant data would potentially help to unmask local disparity. (see map below, from left to right, respectively: SVI for Philly tracts from CDC's nation-level SVI data, CDC's PA-level SVI data, and findSVI's calculation using percentiles within the county)

![image](https://github.com/heli-xu/findSVI/assets/91294567/1eca53e7-b928-48d1-afb4-ac68646775ef)

I'm learning a lot in this discussion. Thanks again for your input, Usama.

**Comment by usamabilal** [comment]
Great, I see what you mean! The summarize step here would be the average of the percentiles, while the analyze step would be the creation of percentiles themselves. The issue here is that "the mean of percentiles using PHL" will difer from "the mean of percentiles using PA" and will differ from "the mean of percentiles using the US" because those percentiles will change, of course. 
For example, in your maps, you can see how the percentiles using philly has a much more spread distribution, with an equal amount of "yellow" and "purple" vs the PA or nationwide which skew towards purple (high SVI).

Now i think we should just give the user the option to use Nationwide (CDC "compliant") statewide (CDC "compliant"), and county/city (new thing that CDC hasnt done). Importantly, i'd set the default to be nationwide or statewide, so people get similar results to SVI.

Now for the vignette, i wouldnt make a big deal of the comparison between PHL vs PA SVIs, since that's less about the substantive side of the SVI and more about the methods we use. You could recycle this vignette to use roughty the same data/figures, but focus on the differences in calculating SVI using different references for the percentiles (nationwide, PA, SVI).

**Comment by heli-xu** [comment]
Ok! I think I was a bit carried away with the "discrepancy" since the percentiles using philly (with more spread distribution) make the difference between communities look clearer, but I agree it's out of the scope of the package here.

> Now for the vignette, i wouldnt make a big deal of the comparison between PHL vs PA SVIs, since that's less about the substantive side of the SVI and more about the methods we use.

For the [updated vignette](https://heli-xu.github.io/findSVI/articles/tract-level_SVI_in_Philly.html), I just replaced pretty much everything with the maps that I showed, which seems enough to make the point. 

> Now i think we should just give the user the option to use Nationwide (CDC "compliant") statewide (CDC "compliant"), and county/city (new thing that CDC hasnt done). Importantly, i'd set the default to be nationwide or statewide, so people get similar results to SVI.

Users do have the option to use nationwide, statewide and county/city data. The `state` argument in [`get_census_data()`](https://heli-xu.github.io/findSVI/reference/get_census_data.html) and [`find_svi()`](https://heli-xu.github.io/findSVI/reference/find_svi.html) is default to nationwide if no states are specified (similar to tidycensus). 

However, the geographic area that SVI is calculated within is depending on what data the users decide to pull. For example, if users are pulling data for "Philadelphia County", the SVI is thereby calculated within Philly; if users are pulling data for "PA", the SVI is calculated within PA. For nationwide/statewide SVI in Philly, users will have to pull nationwide data for nationwide SVI calculation, and from there filter the result for Philly. 

Main considerations behind this design are:
1) Data retrieval is largely following tidycensus style, and having an extra layer of geography-related argument (nationwide, statewide and county) can be confusing and complicate things.
2) findSVI is mostly to complement what CDC is not doing, like SVI at zcta level, and SVI below statewide. Especially for something like nationwide tract-level SVI (with geometry), it'd actually be more convenient to download from CDC database. I thought about just keeping the CDC data files in the package, but that'd be too big.

Hope this makes sense. Thanks!

**Comment by usamabilal** [comment]
> Ok! I think I was a bit carried away with the "discrepancy" since the percentiles using philly (with more spread distribution) make the difference between communities look clearer, but I agree it's out of the scope of the package here.
> 
> > Now for the vignette, i wouldnt make a big deal of the comparison between PHL vs PA SVIs, since that's less about the substantive side of the SVI and more about the methods we use.
> 
> For the [updated vignette](https://heli-xu.github.io/findSVI/articles/tract-level_SVI_in_Philly.html), I just replaced pretty much everything with the maps that I showed, which seems enough to make the point.

Excellent!


> > Now i think we should just give the user the option to use Nationwide (CDC "compliant") statewide (CDC "compliant"), and county/city (new thing that CDC hasnt done). Importantly, i'd set the default to be nationwide or statewide, so people get similar results to SVI.
> 
> Users do have the option to use nationwide, statewide and county/city data. The `state` argument in [`get_census_data()`](https://heli-xu.github.io/findSVI/reference/get_census_data.html) and [`find_svi()`](https://heli-xu.github.io/findSVI/reference/find_svi.html) is default to nationwide if no states are specified (similar to tidycensus).
> 
> However, the geographic area that SVI is calculated within is depending on what data the users decide to pull. For example, if users are pulling data for "Philadelphia County", the SVI is thereby calculated within Philly; if users are pulling data for "PA", the SVI is calculated within PA. For nationwide/statewide SVI in Philly, users will need to pull nationwide/statewide data for the corresponding SVI calculation, and from there filter the result for Philly.
> 
> Main considerations behind this design are:
> 
> 1. Data retrieval is largely following tidycensus style, and having an extra layer of geography-related argument (nationwide, statewide and county) can be confusing and complicate things. For something like nationwide zcta-level SVI in a city, our current approach of "pulling nation data--get nation SVI--filter area of interest" seems to me more intuitive than adding another argument.
> 2. findSVI is mostly to complement what CDC is not doing, like SVI at zcta level, and SVI below statewide. For something like nationwide tract-level SVI (with geometry), it'd actually be more convenient to download from CDC database (I thought about just keeping the CDC data files in the package, but that'd be too big).
> 
> Hope this makes sense. Thanks!

Makes a ton of sense, and from a user perspective I agree entirely with the decision to keep the "sampling frame" (so to speak) to be the same as whatever unit they are pulling from (if Philadelphia County, then Philadelphia, if all of PA, then all of PA).

On point (2), is this because you can't pull tracts for the entire country (or can you?) from tidycensus? I think there's still value in having the same things as CDC, since this means the user doesn't have to go to CDC website, download, import, convert the GEOIDs to something compatible with other tidycensus stuff, etc. In other words ,it streamlines the process, making sure WE control the steps, and therefore reducing user error. Does that make sense?

Thanks again!!

**Comment by heli-xu** [comment]
Thank you for the feedback! Glad the first point makes sense to you.

>On point (2), is this because you can't pull tracts for the entire country (or can you?) from tidycensus? I think there's still value in having the same things as CDC, since this means the user doesn't have to go to CDC website, download, import, convert the GEOIDs to something compatible with other tidycensus stuff, etc. In other words ,it streamlines the process, making sure WE control the steps, and therefore reducing user error. 
 
I agree completely--sorry I might have confused you with this point. Yes we can pull tracts for entire country from tidycensus and our package can calculate nationwide tract-level SVI. It's just with geometry it could take a while to pull the data, but certainly doable. I was only thinking that it might be faster to download the file, but it does make a lot of sense from the standpoint of streamlining the process.
 
What I meant to say in this point (2) was more like a further explanation of point (1), that the package is designed for users to decide "what level data from where" they want in their SVI calculation, without emphasizing/referencing much what level of SVI CDC is doing (whether it's "CDC compliant").   

Hope this addresses your questions...Thanks again for your help!

**Comment by usamabilal** [comment]
Got it! Sounds good
________________________________
